# This is a test workflow for opencdms-test-data

name: tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  matrix-setup:
    strategy:
      matrix:
        os: [windows-latest,macos-latest,ubuntu-latest]
        py-version: ['3.7','3.8','3.9','3.10','3.11']
    runs-on: ${{matrix.os}}

    steps:
      - name: Support longpaths
        if: ${{matrix.os == 'windows-latest'}}
        shell: cmd
        run: git config --global core.longpaths true
      - uses: actions/checkout@v3
        with:
          python-version: ${{matrix.py-version}}

      # Runs a single command using the runners shell
      - name: Installs necessary dependencies
        if: always()
        run: pip3 install -r requirements_dev.txt

      # Runs a set of commands using the runners shell
      - name: Runs tests
        run: pytest tests
